Repository encointer/encointer-wallet-flutter, pull requests merged in 2023-04, with the labels that each got.

#1080 Display all cached communities in the community slider
  app/lib/page/assets/account_or_community/account_or_community_item_horizontal.dart
  app/lib/page/assets/account_or_community/switch_account_or_community.dart
  app/lib/page/assets/index.dart
Labels: A0-ux, A2-technical, B0-low, C0-breaksnothing

#1087 GBD community notification sound
  app/android/app/src/main/res/raw/gbd_chime.mp3
  app/android/app/src/main/res/raw/keep.xml
  app/ios/Resources/notification_sounds/gbd_chime.wav
  app/ios/Resources/notification_sounds/lions_growl.wav
  app/ios/Runner.xcodeproj/project.pbxproj
  app/ios/lions_growl.wav
  app/lib/config/consts.dart
  app/lib/config/prod_community.dart
  app/lib/page-encointer/home_page.dart
  app/lib/page/assets/index.dart
  app/lib/service/meetup/notification_handler.dart
  app/lib/service/notification/lib/src/ceremony_notifications.dart
  app/lib/service/notification/lib/src/notification_plugin.dart
  app/lib/service/substrate_api/account_api.dart
  app/lib/service/tx/lib/src/submit_to_js.dart
  app/lib/service/tx/lib/src/submit_tx_wrappers.dart
  app/lib/store/account/account.dart
  app/test/service/meetup/callback_dispatcher_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1115 Regenerate Podfile.lock with cocoapod v1.12.0
  app/ios/Podfile.lock
Labels: A2-technical, B0-low, C0-breaksnothing

#1117 AggregatedAccountData.global non-nullable
  app/lib/models/ceremonies/ceremonies.dart
  app/lib/models/ceremonies/ceremonies.g.dart
  app/lib/service/substrate_api/encointer/encointer_api.dart
  app/lib/service/tx/lib/src/submit_tx_wrappers.dart
  melos.yaml
Labels: A2-technical, B0-low, C0-breaksnothing

#1086 Generate screenshots in CI
  .github/workflows/android_integration_test.yml
  .github/workflows/ios_integration_test.yml
  .github/workflows/js_ci.yml
  app/lib/page-encointer/ceremony_box/ceremony_box.dart
  app/lib/page/profile/account/account_manage_page.dart
  app/lib/utils/screenshot.dart
  app/test_driver/app_test.dart
  app/test_driver/helpers/other_test.dart
  app/test_driver/helpers/participant_type.dart
  app/test_driver/helpers/real_app_helper.dart
  app/test_driver/helpers/screenshots.dart
  app/test_driver/real_app.dart
  app/test_driver/real_app_test.dart
  app/test_driver/scan_page_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1125 Transfer `developerMode` to `AppSetting` store
  app/lib/modules/settings/logic/app_settings_store.dart
  app/lib/modules/settings/logic/app_settings_store.g.dart
  app/lib/page-encointer/ceremony_box/ceremony_box.dart
  app/lib/page-encointer/ceremony_box/ceremony_info.dart
  app/lib/page-encointer/ceremony_box/components/ceremony_info_and_calendar.dart
  app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
  app/lib/page/assets/index.dart
  app/lib/page/assets/transfer/transfer_page.dart
  app/lib/page/profile/account/account_manage_page.dart
  app/lib/page/profile/contacts/contact_page.dart
  app/lib/page/profile/index.dart
  app/lib/page/qr_scan/qr_scan_page.dart
  app/lib/store/settings.dart
  app/lib/store/settings.g.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#1141 Use `MockIpfsApi` in integration test
  app/lib/mocks/ipfs/ipfs_api.dart
  app/lib/mocks/substrate_api/mock_api.dart
  app/lib/modules/splash/view/splash_view.dart
  app/lib/service/ipfs/http_api.dart
  app/lib/service/ipfs/ipfs_api.dart
  app/lib/service/substrate_api/api.dart
  app/lib/store/encointer/sub_stores/community_store/community_store.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/store/encointer/sub_stores/community_store/community_store_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1145 Cycle gathering QR scan fails because animal is too big on small screens
  app/lib/common/components/logo/participant_avatar.dart
  app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
  app/lib/utils/extensions/layout/layout_extensions.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1124 Localized messages for transaction errors
  app/lib/service/tx/lib/src/submit_to_js.dart
  app/lib/utils/translations/translations_assets.dart
  app/lib/utils/translations/translations_transaction.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1073 Replace js-ss58 encoding with the dart version and derive addresses from pubKey on the fly
  app/js_service_encointer/src/service/account.js
  app/lib/common/components/account_select_list.dart
  app/lib/common/components/address_input_field.dart
  app/lib/mocks/storage/mock_local_storage.dart
  app/lib/modules/account/logic/new_account_store.dart
  app/lib/page/assets/index.dart
  app/lib/page/assets/receive/receive_page.dart
  app/lib/page/assets/transfer/payment_confirmation_page/components/payment_overview.dart
  app/lib/page/assets/transfer/payment_confirmation_page/index.dart
  app/lib/page/assets/transfer/transfer_page.dart
  app/lib/page/network_select_page.dart
  app/lib/page/profile/account/account_manage_page.dart
  app/lib/page/profile/contacts/account_share_page.dart
  app/lib/page/profile/contacts/contact_detail_page.dart
  app/lib/page/profile/contacts/contact_page.dart
  app/lib/page/profile/contacts/contacts_page.dart
  app/lib/page/qr_scan/qr_scan_service.dart
  app/lib/page/reap_voucher/reap_voucher_page.dart
  app/lib/service/substrate_api/account_api.dart
  app/lib/store/account/account.dart
  app/lib/store/account/account.g.dart
  app/lib/store/app.dart
  app/lib/store/settings.dart
  app/lib/utils/format.dart
  app/lib/utils/local_storage.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1111 Remove ss58-prefix override and use the network-specific prefix for address display
  app/js_service_encointer/src/service/account.js
  app/js_service_encointer/src/service/settings.js
  app/lib/config/consts.dart
  app/lib/mocks/substrate_api/mock_encointer_api.dart
  app/lib/models/ceremonies/ceremonies.dart
  app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
  app/lib/page-encointer/meetup/scan_claim_qr_code.dart
  app/lib/service/substrate_api/account_api.dart
  app/lib/service/substrate_api/encointer/encointer_api.dart
  app/lib/service/tx/lib/src/submit_tx_wrappers.dart
  app/lib/store/encointer/encointer.dart
  app/lib/utils/format.dart
Labels: A0-ux, A2-technical, B0-low, C1-breaksapi

#1175 Create package `ew_http` for HTTP REQUEST
  packages/ew_http/README.md
  packages/ew_http/analysis_options.yaml
  packages/ew_http/lib/ew_http.dart
  packages/ew_http/lib/src/ew_http.dart
  packages/ew_http/lib/src/exceptions/exceptions.dart
  packages/ew_http/pubspec.yaml
  packages/ew_http/test/ew_http_test.dart
  packages/ew_http/test/test_model.dart
Labels: A2-technical, B2-critical, C0-breaksnothing
