Repository encointer/encointer-wallet-flutter, pull requests merged in 2023-03, with the labels that each got.

#1068 Add CI label check
  .github/workflows/check_labels.yml
Labels: A2-technical, B0-low, C0-breaksnothing

#1066 Allow participants to unregister
  app/lib/models/ceremonies/ceremonies.dart
  app/lib/modules/meetup_location/view/meetup_location_view.dart
  app/lib/page-encointer/ceremony_box/ceremony_box.dart
  app/lib/page-encointer/ceremony_box/components/unregister_link_button.dart
  app/lib/page/assets/index.dart
  app/lib/service/substrate_api/encointer/encointer_api.dart
  app/lib/service/tx/lib/src/params.dart
  app/lib/service/tx/lib/src/submit_tx_wrappers.dart
  app/lib/store/encointer/sub_stores/encointer_account_store/encointer_account_store.dart
  app/lib/store/encointer/sub_stores/encointer_account_store/encointer_account_store.g.dart
  app/lib/utils/alerts/app_alert.dart
  app/lib/utils/translations/translations.dart
  app/lib/utils/translations/translations_encointer.dart
  app/lib/utils/translations/translations_home.dart
  app/lib/utils/translations/translations_transaction.dart
  app/test_driver/helpers/real_app_helper.dart
  app/test_driver/real_app_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1076 Fix flaky integration test: share and change account name
  app/lib/page/profile/account/account_manage_page.dart
  app/test_driver/helpers/other_test.dart
  app/test_driver/real_app_test.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1082 Fix packages test for github actions
  packages/ew_format/pubspec.yaml
  packages/ew_models/pubspec.yaml
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1063 Hide mnemonic and rawSeed in logs
  app/lib/service/log/log_service.dart
  app/lib/service/substrate_api/core/js_api.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1052 Add dart pubKey -> ss58-address encoding
  app/lib/utils/format.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/utils/format_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1088 Remove unused methods and vars in NotificationPlugin
  app/lib/service/notification/lib/src/notification_plugin.dart
Labels: A2-technical, B1-medium, C1-breaksapi

#1100 Fix `melos bootstrap` error in github actions
  pubspec.lock
  pubspec.yaml
Labels: A1-bugfix, B1-medium, C0-breaksnothing
