Repository encointer/encointer-wallet-flutter, pull requests merged in 2023-05, with the labels that each got.

#1167 [launch.json] distinguished configuration for Android and iOS
  .vscode/launch.json
Labels: enhancement, A2-technical, B1-medium, C0-breaksnothing

#1165 Fixed app crash on Android API < 26
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/kotlin/org/encointer/wallet/MainActivity.kt
Labels: bug, Android, A1-bugfix, B2-critical, C0-breaksnothing

#1155 Change language in integration test
  app/lib/main.dart
  app/lib/modules/settings/logic/app_settings_store.dart
  app/lib/modules/settings/logic/app_settings_store.g.dart
  app/lib/modules/settings/service/lang_service.dart
  app/lib/modules/settings/view/lang_page.dart
  app/lib/page/profile/index.dart
  app/test_driver/helpers/command/real_app_command.dart
  app/test_driver/helpers/command/real_app_functions.dart
  app/test_driver/helpers/screenshots.dart
  app/test_driver/real_app.dart
  app/test_driver/real_app_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1140 Unit test 'Preferences storage test' for ew-storage
  packages/ew_storage/test/preferences_storage_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1194 Forward mail to bugreports instead of trello directly
  app/lib/common/components/launch/send_to_trello_list_tile.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1163 Show mock announcements on homepage with developer options
  app/lib/common/components/logo/community_icon.dart
  app/lib/models/announcement/announcement.dart
  app/lib/models/announcement/announcement.g.dart
  app/lib/page/assets/announcement/logic/announcement_card_store.dart
  app/lib/page/assets/announcement/logic/announcement_card_store.g.dart
  app/lib/page/assets/announcement/logic/announcement_store.dart
  app/lib/page/assets/announcement/logic/announcement_store.g.dart
  app/lib/page/assets/announcement/view/announcement_view.dart
  app/lib/page/assets/announcement/widgets/announcement_card.dart
  app/lib/page/assets/announcement/widgets/publisher_and_community_icon.dart
  app/lib/page/assets/index.dart
  app/test_driver/helpers/other_test.dart
  app/test_driver/helpers/real_app_helper.dart
  app/test_driver/real_app_test.dart
Labels: A0-ux, A2-technical, B0-low, C0-breaksnothing

#1188 Send receive QR code to printer
  .vscode/settings.json
  app/assets/images/assets/leu_steller_bg.png
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/lib/common/components/qr_code_view/qr_code_image_view.dart
  app/lib/gen/assets.gen.dart
  app/lib/page-encointer/home_page.dart
  app/lib/page/assets/index.dart
  app/lib/page/assets/qr_code_printing/pages/qr_code_share_or_print_view.dart
  app/lib/page/assets/qr_code_printing/widgets/preview_pdf_and_print.dart
  app/lib/page/assets/qr_code_printing/widgets/store/preview_pdf_and_print_store.dart
  app/lib/page/assets/qr_code_printing/widgets/store/preview_pdf_and_print_store.g.dart
  app/lib/page/assets/receive/receive_page.dart
  app/lib/page/profile/contacts/account_share_page.dart
  app/lib/router/app_router.dart
  app/lib/utils/translations/translations_assets.dart
  app/pubspec.lock
  app/pubspec.yaml
  melos.yaml
Labels: A0-ux, B0-low, C0-breaksnothing

#1204 Take screenshots for every language in integration test
  app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
  app/test_driver/app_test.dart
  app/test_driver/helpers/add_delay.dart
  app/test_driver/helpers/command/real_app_command.dart
  app/test_driver/helpers/enums/participant_type.dart
  app/test_driver/helpers/extension/screenshot_driver.dart
  app/test_driver/helpers/extension/screenshot_driver_extension.dart
  app/test_driver/helpers/extension/screenshots_name.dart
  app/test_driver/helpers/helper.dart
  app/test_driver/helpers/other_test.dart
  app/test_driver/helpers/real_app_helper.dart
  app/test_driver/real_app.dart
  app/test_driver/real_app/account/account_helper.dart
  app/test_driver/real_app/account/account_test.dart
  app/test_driver/real_app/account_entry/account_entry_test.dart
  app/test_driver/real_app/account_manage/account_manage_helper.dart
  app/test_driver/real_app/account_manage/account_manage_test.dart
  app/test_driver/real_app/ceremony/ceremony_helper.dart
  app/test_driver/real_app/ceremony/cremony_test.dart
  app/test_driver/real_app/contact/contact_helper.dart
  app/test_driver/real_app/contact/contact_test.dart
  app/test_driver/real_app/home/home_helper.dart
  app/test_driver/real_app/home/home_test.dart
  app/test_driver/real_app/language/language_test.dart
  app/test_driver/real_app/navigate.dart
  app/test_driver/real_app/network/network_test.dart
  app/test_driver/real_app/profile/profile_helper.dart
  app/test_driver/real_app/profile/profile_test.dart
  app/test_driver/real_app/real_app.dart
  app/test_driver/real_app/receive/receive_test.dart
  app/test_driver/real_app/transfer/transfer_helper.dart
  app/test_driver/real_app/transfer/transfer_test.dart
  app/test_driver/real_app_test.dart
  app/test_driver/scan_page_test.dart
  melos.yaml
  scripts/install_melos.sh
Labels: A2-technical, B0-low, C0-breaksnothing

#990 Local OS biometric(Pin code) authentication API
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/kotlin/org/encointer/wallet/MainActivity.kt
  app/android/build.gradle
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/ios/Runner/Info.plist
  app/lib/common/components/buttons/circle_button.dart
  app/lib/common/components/buttons/close_button.dart
  app/lib/common/components/grid_view/grid_view_count.dart
  app/lib/gen/assets.gen.dart
  app/lib/main.dart
  app/lib/modules/account/logic/new_account_store.dart
  app/lib/modules/account/view/handle_new_account_result_mixin.dart
  app/lib/modules/login/logic/login_store.dart
  app/lib/modules/login/logic/login_store.g.dart
  app/lib/modules/login/login.dart
  app/lib/modules/login/view/login_view.dart
  app/lib/modules/login/widget/login_button.dart
  app/lib/modules/login/widget/pin_dots.dart
  app/lib/modules/login/widget/pin_keyboard.dart
  app/lib/modules/login/widget/widget.dart
  app/lib/modules/modules.dart
  app/lib/modules/settings/logic/app_settings_store.dart
  app/lib/modules/settings/logic/app_settings_store.g.dart
  app/lib/modules/settings/service/app_service.dart
  app/lib/modules/settings/settings.dart
  app/lib/modules/settings/view/lang_page.dart
  app/lib/modules/splash/view/splash_view.dart
  app/lib/page/network_select_page.dart
  app/lib/page/profile/account/change_password_page.dart
  app/lib/page/profile/index.dart
  app/lib/router/app_router.dart
  app/lib/service/substrate_api/account_api.dart
  app/lib/store/app.dart
  app/lib/store/settings.dart
  app/lib/store/settings.g.dart
  app/lib/utils/alerts/app_alert.dart
  app/lib/utils/alerts/password_input_dialog.dart
  app/lib/utils/translations/translations_account.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/mock/flutter_secure_storage.dart
  app/test/store/account_test.dart
  app/test/store/app_test.dart
  app/test/store/encointer/encointer_test.dart
  app/test/store/encointer/sub_stores/community_store/community_store_test.dart
  app/test/store/settings_test.dart
  app/test_driver/app.dart
  app/test_driver/real_app.dart
  packages/ew_storage/lib/ew_storage.dart
  packages/ew_storage/test/preferences_storage_test.dart
  packages/ew_storage/test/secure_storage_test.dart
Labels: A0-ux, B1-medium, C0-breaksnothing

#1227 TxConfirmPage printscreen should have the tick visible
  app/lib/config.dart
  app/lib/page/assets/transfer/payment_confirmation_page/index.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1182 Gathering: Suggest postponing sending claims only if the device is offline
  app/lib/page-encointer/meetup/ceremony_step3_finish.dart
  app/lib/utils/translations/translations_encointer.dart
  app/pubspec_overrides.yaml
Labels: A0-ux, B0-low, C0-breaksnothing

#1180 mock back end for announcements
  app/lib/data/common_services/models/network/api_response.dart
  app/lib/data/common_services/network/api_services.dart
  app/lib/data/remote/announcements/announcements_api.dart
  app/lib/data/remote/announcements/announcements_api_services.dart
  app/lib/mocks/announcements/mock_announcements_api.dart
  app/lib/page/assets/announcement/logic/announcement_store.dart
  app/lib/page/assets/announcement/logic/announcement_store.g.dart
  app/lib/page/assets/announcement/view/announcement_view.dart
  app/lib/page/assets/index.dart
  app/lib/utils/extensions/string/string_extensions.dart
  app/lib/utils/translations/translations_home.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/data/common_services/network/api_services_test.dart
  app/test/data/common_services/remote/announcements/announcements_api_test.dart
  app/test/models/announcement/announcement_model_test.dart
Labels: enhancement, F0-pure flutter, A0-ux, B1-medium, C0-breaksnothing

#1219 Implement and integrate dart native ss58-decode
  app/js_service_encointer/.yarn/cache/@polkadot-util-npm-0.41.1-5c087e9541-da2ccd1828.zip
  app/js_service_encointer/.yarn/cache/@polkadot-wasm-crypto-npm-0.5.1-3d5d2049f3-824827860a.zip
  app/js_service_encointer/.yarn/cache/@polkadot-wasm-schnorrkel-npm-0.3.1-521e36bc30-463d81250e.zip
  app/js_service_encointer/.yarn/cache/@types-deasync-npm-0.1.2-2ec0939ae8-28a49e42c0.zip
  app/js_service_encointer/.yarn/cache/@types-ip-regex-npm-3.0.0-37ff8581dd-fd1750553b.zip
  app/js_service_encointer/.yarn/cache/async-limiter-npm-1.0.1-7e6819bcdb-2b849695b4.zip
  app/js_service_encointer/.yarn/cache/bip39-npm-2.6.0-c369effd70-5c857919fd.zip
  app/js_service_encointer/.yarn/cache/blakejs-npm-1.1.1-0c18cf8738-77a0875af4.zip
  app/js_service_encointer/.yarn/cache/camel-case-npm-3.0.0-d87e5afe35-4190ed6ab8.zip
  app/js_service_encointer/.yarn/cache/canvas-renderer-npm-2.1.1-73a1fced83-6bb28714be.zip
  app/js_service_encointer/.yarn/cache/change-case-npm-3.1.0-f29e0003bb-d6f9f90a5f.zip
  app/js_service_encointer/.yarn/cache/constant-case-npm-2.0.0-b287998b5e-893c793a42.zip
  app/js_service_encointer/.yarn/cache/cuint-npm-0.2.2-3990651cc6-b8127a93a7.zip
  app/js_service_encointer/.yarn/cache/dot-case-npm-2.1.1-f591fd2e48-5c9d937245.zip
  app/js_service_encointer/.yarn/cache/header-case-npm-1.0.1-3a0bfdc9cc-fe1cc9a555.zip
  app/js_service_encointer/.yarn/cache/is-lower-case-npm-1.1.3-2f95af21e5-55a2a9fe38.zip
  app/js_service_encointer/.yarn/cache/is-upper-case-npm-1.1.2-0ce2928e8f-c85805dfb9.zip
  app/js_service_encointer/.yarn/cache/isomorphic-fetch-npm-2.2.1-46b4db5d7b-bb5daa7c37.zip
  app/js_service_encointer/.yarn/cache/isomorphic-ws-npm-4.0.1-aa39192848-d7190eadef.zip
  app/js_service_encointer/.yarn/cache/jdenticon-npm-2.2.0-fddf620bb1-2aeae02a10.zip
  app/js_service_encointer/.yarn/cache/lower-case-first-npm-1.0.2-9d3e4f27ec-97eb5ce689.zip
  app/js_service_encointer/.yarn/cache/lower-case-npm-1.1.4-9880e9dcb0-1ca9393b5e.zip
  app/js_service_encointer/.yarn/cache/no-case-npm-2.3.2-5403767f87-8564877319.zip
  app/js_service_encointer/.yarn/cache/node-fetch-npm-1.7.3-eb8372f991-3bb0528c05.zip
  app/js_service_encointer/.yarn/cache/oo7-npm-0.7.12-40550ed0d0-90c9899c9f.zip
  app/js_service_encointer/.yarn/cache/oo7-substrate-npm-0.8.0-3f654b7e13-7cfa2c0aa3.zip
  app/js_service_encointer/.yarn/cache/param-case-npm-2.1.1-e0aef3c289-3a63dcb8d8.zip
  app/js_service_encointer/.yarn/cache/pascal-case-npm-2.0.1-97fc825dec-4c539bf556.zip
  app/js_service_encointer/.yarn/cache/path-case-npm-2.1.1-fafa84599b-eb1da508c2.zip
  app/js_service_encointer/.yarn/cache/sentence-case-npm-2.1.1-ffe9ddf186-ce5ca48804.zip
  app/js_service_encointer/.yarn/cache/snake-case-npm-2.1.0-4134611dfc-7e42b48411.zip
  app/js_service_encointer/.yarn/cache/ss58-npm-1.0.2-f112d94425-3c72525b48.zip
  app/js_service_encointer/.yarn/cache/swap-case-npm-1.1.2-2d186deabd-37b0c4988e.zip
  app/js_service_encointer/.yarn/cache/text-encoding-npm-0.7.0-ff0c4af052-b6109a843f.zip
  app/js_service_encointer/.yarn/cache/text-encoding-polyfill-npm-0.6.7-ce5140c54b-8e5b45154f.zip
  app/js_service_encointer/.yarn/cache/title-case-npm-2.1.1-d828015841-e88ddfc460.zip
  app/js_service_encointer/.yarn/cache/unorm-npm-1.6.0-43467eccf1-9a86546256.zip
  app/js_service_encointer/.yarn/cache/upper-case-first-npm-1.1.2-a07735d821-7467267967.zip
  app/js_service_encointer/.yarn/cache/upper-case-npm-1.1.3-061d82781f-991c845de7.zip
  app/js_service_encointer/.yarn/cache/whatwg-fetch-npm-3.6.2-4bdf324792-ee976b7249.zip
  app/js_service_encointer/.yarn/cache/ws-npm-6.2.2-ca62a10fa0-aec3154ec5.zip
  app/js_service_encointer/.yarn/cache/xxhashjs-npm-0.2.2-70e0154c76-cf6baf05ba.zip
  app/js_service_encointer/package.json
  app/js_service_encointer/src/service/account.js
  app/js_service_encointer/yarn.lock
  app/lib/page-encointer/meetup/scan_claim_qr_code.dart
  app/lib/page/assets/transfer/transfer_page.dart
  app/lib/page/profile/contacts/contact_page.dart
  app/lib/service/substrate_api/account_api.dart
  app/lib/utils/format.dart
  app/test/utils/format_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing
