Repository encointer/encointer-wallet-flutter, pull requests merged in 2023-07, with the labels that each got.

#1322 Fix inconsistent loading of community messages
  app/lib/page/assets/announcement/logic/announcement_store.dart
  app/lib/page/assets/announcement/logic/announcement_store.g.dart
  app/lib/page/assets/announcement/view/announcement_view.dart
Labels: F0-pure flutter, A1-bugfix, B1-medium, C0-breaksnothing

#1327 Fix: Notification icon does not render in production
  app/android/app/src/main/res/drawable/app_icon.png
  app/android/app/src/main/res/drawable/launcher_icon.png
  app/lib/service/notification/lib/src/notification_plugin.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1333 Collect contacts automatically from invoices data (scan)
  app/lib/page/qr_scan/qr_scan_page.dart
  app/lib/page/qr_scan/qr_scan_service.dart
  app/test_driver/app/dev_qr_codes/dev_qr_codes_test.dart
  app/test_driver/app_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1338 fix scanning invoice qr code from `TransferPage`
  app/lib/page/qr_scan/qr_scan_page.dart
  app/lib/page/qr_scan/qr_scan_service.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1303 [Bazaar] Create UI of a single business page
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/models/bazaar/businesses.dart
  app/lib/models/bazaar/single_business.dart
  app/lib/models/bazaar/single_business.g.dart
  app/lib/page-encointer/bazaar/0_main/bazaar_main.dart
  app/lib/page-encointer/new_bazaar/businesses/logic/businesses_store.dart
  app/lib/page-encointer/new_bazaar/businesses/logic/businesses_store.g.dart
  app/lib/page-encointer/new_bazaar/businesses/view/businesses_view.dart
  app/lib/page-encointer/new_bazaar/businesses/widgets/businesses_card.dart
  app/lib/page-encointer/new_bazaar/businesses/widgets/dropdown_widget.dart
  app/lib/page-encointer/new_bazaar/businesses/widgets/empty_businesses.dart
  app/lib/page-encointer/new_bazaar/single_business/logic/single_business_store.dart
  app/lib/page-encointer/new_bazaar/single_business/logic/single_business_store.g.dart
  app/lib/page-encointer/new_bazaar/single_business/views/single_business_view.dart
  app/lib/page-encointer/new_bazaar/single_business/widgets/business_detail_address_widget.dart
  app/lib/page-encointer/new_bazaar/single_business/widgets/business_detail_text_widget.dart
  app/lib/page-encointer/new_bazaar/single_business/widgets/map_button.dart
  app/lib/page-encointer/new_bazaar/single_business/widgets/single_business_detail.dart
  app/lib/page-encointer/new_bazaar/widgets/businesses_card.dart
  app/pubspec.yaml
  app/test/store/bazaar/businesses_store_test.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1336 Refine GBD community colors
  app/lib/modules/settings/logic/app_settings_store.dart
  app/lib/modules/settings/logic/app_settings_store.g.dart
  app/lib/page/assets/index.dart
  app/lib/page/assets/transfer/transfer_page.dart
  app/lib/page/profile/account/change_password_page.dart
  app/lib/theme/custom/colors/app_colors.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1340 Add screenshots of transfer history in CI
  app/lib/modules/transfer/widgets/transactions_list.dart
  app/test_driver/app/app.dart
  app/test_driver/app/navigate.dart
  app/test_driver/app/transfer_history/transfer_history_test.dart
  app/test_driver/app_test.dart
  app/test_driver/helpers/extension/screenshots_name.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1329 Remove redundant `send attestation` button if they were already sent at the end of the meetup
  app/lib/store/encointer/encointer.dart
  app/lib/store/encointer/encointer.g.dart
Labels: A0-ux, A2-technical, B1-medium, C0-breaksnothing

#1350 Show encointer logo instead community logo if announcement is global
  app/lib/models/announcement/announcement.dart
  app/lib/page/assets/announcement/widgets/announcement_card.dart
  app/lib/page/assets/announcement/widgets/publisher_and_community_icon.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1359 [Bazaar] fix businesses padding
  app/lib/page-encointer/new_bazaar/businesses/widgets/businesses_card.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1360 Remove announcement error dialog
  app/lib/page/assets/announcement/logic/announcement_store.dart
  app/lib/page/assets/announcement/logic/announcement_store.g.dart
  app/lib/page/assets/announcement/view/announcement_view.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1370 Remove old package `animated_check` and implement it ourselves
  app/lib/common/components/animation/animated_check.dart
  app/lib/page/assets/transfer/payment_confirmation_page/index.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: A2-technical, B0-low, C0-breaksnothing

#1363 Text too big in Ru language
  app/lib/l10n/arb/app_ru.arb
  app/lib/page/assets/qr_code_printing/pages/qr_code_share_or_print_view.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1265 [Bazaar] add back end to bazaar mainpage
  app/lib/common/components/logo/community_icon.dart
  app/lib/common/components/map/encointer_map.dart
  app/lib/config/consts.dart
  app/lib/mocks/mock_bazaar_data.dart
  app/lib/models/bazaar/businesses.dart
  app/lib/models/bazaar/businesses.g.dart
  app/lib/modules/transfer/view/transfer_history_view.dart
  app/lib/page-encointer/bazaar/0_main/bazaar_main.dart
  app/lib/page-encointer/common/community_chooser_on_map.dart
  app/lib/page-encointer/new_bazaar/businesses/logic/businesses_store.dart
  app/lib/page-encointer/new_bazaar/businesses/logic/businesses_store.g.dart
  app/lib/page-encointer/new_bazaar/businesses/view/businesses_view.dart
  app/lib/page-encointer/new_bazaar/businesses/widgets/businesses_card.dart
  app/lib/page-encointer/new_bazaar/businesses/widgets/dropdown_widget.dart
  app/lib/page-encointer/new_bazaar/businesses/widgets/empty_businesses.dart
  app/lib/page-encointer/new_bazaar/single_business/views/single_business_view.dart
  app/lib/page/assets/account_or_community/switch_account_or_community.dart
  app/lib/page/assets/announcement/view/announcement_view.dart
  app/lib/page/assets/index.dart
  app/lib/page/network_select_page.dart
  app/lib/presentation/home/views/home_page.dart
  app/lib/router/app_router.dart
  app/lib/service/substrate_api/encointer/encointer_api.dart
  app/lib/service/substrate_api/encointer/encointer_dart_api.dart
  app/lib/store/encointer/sub_stores/bazaar_store/bazaar_store.dart
  app/lib/utils/extensions/extensions.dart
  app/lib/utils/extensions/iterables/iterables_extensions.dart
  app/lib/utils/fetch_status.dart
  app/test/mock/api/mock_encointer_api.dart
  app/test/store/bazaar/businesses_store_test.dart
Labels: A0-ux, B1-medium, C0-breaksnothing

#1330 Add back end to a single business page
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/models/bazaar/businesses.dart
  app/lib/models/bazaar/businesses.g.dart
  app/lib/models/bazaar/ipfs_product.dart
  app/lib/models/bazaar/ipfs_product.g.dart
  app/lib/models/bazaar/item_offered.dart
  app/lib/models/bazaar/item_offered.g.dart
  app/lib/models/bazaar/single_business.dart
  app/lib/models/bazaar/single_business.g.dart
  app/lib/page-encointer/bazaar/0_main/bazaar_main.dart
  app/lib/page-encointer/new_bazaar/businesses/logic/businesses_store.dart
  app/lib/page-encointer/new_bazaar/businesses/logic/businesses_store.g.dart
  app/lib/page-encointer/new_bazaar/businesses/view/businesses_view.dart
  app/lib/page-encointer/new_bazaar/businesses/widgets/businesses_card.dart
  app/lib/page-encointer/new_bazaar/single_business/logic/single_business_store.dart
  app/lib/page-encointer/new_bazaar/single_business/logic/single_business_store.g.dart
  app/lib/page-encointer/new_bazaar/single_business/views/single_business_view.dart
  app/lib/page-encointer/new_bazaar/single_business/widgets/business_detail_text_widget.dart
  app/lib/page-encointer/new_bazaar/single_business/widgets/single_business_detail.dart
  app/lib/page/assets/index.dart
  app/lib/presentation/home/views/home_page.dart
  app/lib/service/substrate_api/encointer/encointer_api.dart
  app/lib/service/substrate_api/encointer/encointer_dart_api.dart
  app/test/store/bazaar/businesses_store_test.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#1368 Bazaar - Write test of a single business page mock
  app/test/mock/data/mock_single_business_data.dart
  app/test/mock/mock.dart
  app/test/models/single_business/single_business_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1367 Test for a single business page back end
  app/lib/mocks/mock_bazaar_data.dart
  app/lib/models/bazaar/offering_data.dart
  app/lib/models/bazaar/offering_data.g.dart
  app/lib/page-encointer/new_bazaar/businesses/logic/business_utils.dart
  app/lib/page-encointer/new_bazaar/businesses/view/businesses_view.dart
  app/lib/page-encointer/new_bazaar/businesses/widgets/businesses_card.dart
  app/lib/page-encointer/new_bazaar/single_business/views/single_business_view.dart
  app/lib/page-encointer/new_bazaar/single_business/widgets/single_business_detail.dart
  app/test/mock/api/mock_encointer_api.dart
  app/test/mock/data/mock_encointer_data.dart
  app/test/store/bazaar/single_business_view_store_test.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#1369 try fetch English announcements if the app language's are not available
  app/lib/page/assets/announcement/logic/announcement_store.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#1362 Fix: Announcement share as deep link
  app/lib/page/assets/announcement/widgets/announcement_card.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1361 Asks enabling biometric authentication although I already enabled it previously
  app/lib/modules/login/service/login_service.dart
  app/lib/modules/settings/service/app_service.dart
  app/test_driver/helpers/command/app_functions.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1376 [transfer_history] fix display names of contacts created pre-1.9.1
  app/lib/models/transfer/transfer_history.dart
  app/lib/modules/transfer/widgets/transaction_card.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1386 adjust `scannedAttendeesCount` according to device settings
  app/lib/page-encointer/meetup/scan_claim_qr_code.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1382 Try fix gathering scanner bug
  app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
  app/lib/page-encointer/meetup/scan_claim_qr_code.dart
Labels: A1-bugfix, B2-critical, C0-breaksnothing

#1395 More robust transfer history
  app/lib/models/transfer/transfer_history.dart
  app/lib/modules/transfer/logic/transfer_history_view_store.dart
  app/lib/modules/transfer/widgets/transaction_card.dart
  app/lib/modules/transfer/widgets/transactions_list.dart
Labels: A1-bugfix, B2-critical, C0-breaksnothing

#1413 update bazaar business store unit test to match business logic
  app/test/store/bazaar/businesses_store_test.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1387 Fix: `TransferPage` animation controller error
  app/lib/common/components/animation/animated_check.dart
  app/lib/page/assets/transfer/payment_confirmation_page/index.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#1397 Fix displaying contacts in `AddressInputField`
  app/lib/common/components/address_input_field.dart
  app/lib/modules/transfer/widgets/transactions_list.dart
  app/lib/page/profile/contacts/contact_list_page.dart
  app/lib/page/qr_scan/qr_scan_service.dart
  app/lib/store/settings.dart
  app/lib/store/settings.g.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1419 Ensure the whole QR-code is displayed on receive page
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/page/assets/receive/receive_page.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1394 add unit tests for `Transaction` model
  app/test/models/transfer/transfer_history_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1415 Changed registering information text for newbies
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
Labels: A0-ux, A2-technical, B0-low, C0-breaksnothing

#1423 Contact list: make the whole `ListTile` clickable instead of just arrow icon button
  app/lib/page/profile/contacts/contacts_page.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1414 Added onError property to `submitTx`
  app/lib/page/assets/transfer/payment_confirmation_page/index.dart
  app/lib/service/tx/lib/src/submit_to_js.dart
  app/lib/service/tx/lib/src/submit_tx_wrappers.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1364 Set and use all the `TextStyles` inside `Theme`
  app/lib/common/components/address_input_field.dart
  app/lib/common/components/buttons/circle_button.dart
  app/lib/common/components/encointer_text_form_field.dart
  app/lib/common/components/error/error_view.dart
  app/lib/common/components/gradient_elements.dart
  app/lib/common/components/launch/send_to_trello_list_tile.dart
  app/lib/common/components/qr_code_view/qr_code_image_view.dart
  app/lib/common/components/rounded_button.dart
  app/lib/l10n/arb/app_ru.arb
  app/lib/modules/account/view/add_account_view.dart
  app/lib/modules/account/view/create_account_entry_view.dart
  app/lib/modules/account/view/create_account_view.dart
  app/lib/modules/account/view/create_pin_view.dart
  app/lib/modules/account/view/import_account_view.dart
  app/lib/modules/account/widgets/pin_info.dart
  app/lib/modules/transfer/view/transfer_history_view.dart
  app/lib/modules/transfer/widgets/transaction_card.dart
  app/lib/modules/transfer/widgets/transactions_empty.dart
  app/lib/page-encointer/bazaar/bazaar_main.dart
  app/lib/page-encointer/bazaar/businesses/widgets/businesses_card.dart
  app/lib/page-encointer/bazaar/businesses/widgets/empty_businesses.dart
  app/lib/page-encointer/bazaar/single_business/widgets/map_button.dart
  app/lib/page-encointer/bazaar/single_business/widgets/single_business_detail.dart
  app/lib/page-encointer/ceremony_box/ceremony_info.dart
  app/lib/page-encointer/ceremony_box/components/ceremony_count_down.dart
  app/lib/page-encointer/ceremony_box/components/ceremony_schedule.dart
  app/lib/page-encointer/ceremony_box/components/unregister_link_button.dart
  app/lib/page-encointer/ceremony_box/meetup_info/components/ceremony_notification.dart
  app/lib/page-encointer/common/community_chooser_panel.dart
  app/lib/page-encointer/meetup/ceremony_step1_count.dart
  app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
  app/lib/page-encointer/meetup/ceremony_step3_finish.dart
  app/lib/page-encointer/meetup/scan_claim_qr_code.dart
  app/lib/page/assets/account_or_community/account_or_community_item_horizontal.dart
  app/lib/page/assets/account_or_community/switch_account_or_community.dart
  app/lib/page/assets/announcement/widgets/announcement_card.dart
  app/lib/page/assets/index.dart
  app/lib/page/assets/qr_code_printing/pages/qr_code_share_or_print_view.dart
  app/lib/page/assets/receive/receive_page.dart
  app/lib/page/assets/transfer/payment_confirmation_page/components/payment_overview.dart
  app/lib/page/assets/transfer/payment_confirmation_page/index.dart
  app/lib/page/assets/transfer/transfer_page.dart
  app/lib/page/assets/transfer/tx_detail.dart
  app/lib/page/network_select_page.dart
  app/lib/page/profile/about_page.dart
  app/lib/page/profile/account/account_manage_page.dart
  app/lib/page/profile/account/change_password_page.dart
  app/lib/page/profile/account/export_result_page.dart
  app/lib/page/profile/contacts/account_share_page.dart
  app/lib/page/profile/contacts/contact_detail_page.dart
  app/lib/page/profile/contacts/contacts_page.dart
  app/lib/page/profile/index.dart
  app/lib/page/reap_voucher/reap_voucher_page.dart
  app/lib/theme/custom/custom_theme.dart
  app/lib/theme/custom/typography/typography_theme.dart
Labels: A0-ux, B1-medium, C0-breaksnothing

#1428 TransferPage: avoid opening qr-scanner when clicking on the empty spaces next to the scanner icon
  app/lib/common/components/form/scrollable_form.dart
  app/lib/page/assets/transfer/transfer_page.dart
  app/test_driver/app/voucher/voucher_integration_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1433 Replace the dominant `Start Gathering` button if the meetup has been completed with a smaller `Restart Gathering` button
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/page-encointer/ceremony_box/ceremony_box.dart
  app/lib/store/encointer/encointer.dart
  app/lib/store/encointer/encointer.g.dart
  app/test_driver/app/ceremony/cremony_test.dart
  packages/ew_test_keys/lib/src/ew_test_key_names.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1427 [transfer_history] make address copyable and update layout to prevent render overflows
  app/lib/modules/transfer/widgets/transaction_card.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1426 Fix bazaar decoding errors
  app/lib/models/bazaar/single_business.dart
  app/lib/page-encointer/bazaar/businesses/logic/business_utils.dart
  app/lib/page-encointer/bazaar/businesses/widgets/businesses_card.dart
  app/lib/page-encointer/bazaar/single_business/views/single_business_view.dart
  app/lib/page-encointer/bazaar/single_business/widgets/single_business_detail.dart
  packages/ew_http/lib/src/ew_http.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing
