Repository encointer/encointer-wallet-flutter, pull requests merged in 2023-08, with the labels that each got.

#1439 Fix: balance can't be fetched after changing account
  app/lib/page/assets/index.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1440 removed unused translations
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
Labels: A2-technical, B0-low, C0-breaksnothing

#1436 [Bazaar] Remove white background from Lion Icon
  app/assets/images/assets/lion_icon_colored.png
  app/assets/images/assets/lion_icon_uncolored.png
  app/lib/gen/assets.gen.dart
  app/lib/page-encointer/bazaar/single_business/widgets/map_button.dart
  app/lib/page-encointer/bazaar/single_business/widgets/single_business_detail.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1432 Ask for authentication the first time the private key is needed and when deleting/exporting accounts
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/modules/account/logic/new_account_store.dart
  app/lib/modules/account/view/handle_new_account_result_mixin.dart
  app/lib/modules/account/view/import_account_view.dart
  app/lib/modules/login/logic/login_store.dart
  app/lib/modules/login/view/login_dialog.dart
  app/lib/modules/splash/view/splash_view.dart
  app/lib/page/assets/transfer/payment_confirmation_page/index.dart
  app/lib/page/profile/account/change_password_page.dart
  app/lib/page/profile/index.dart
  app/lib/page/reap_voucher/reap_voucher_page.dart
  app/lib/service/substrate_api/encointer/encointer_api.dart
  app/lib/service/tx/lib/src/submit_to_js.dart
  app/lib/service/tx/lib/src/submit_tx_wrappers.dart
  app/lib/store/settings.dart
  app/lib/store/settings.g.dart
  app/test/mock/api/mock_encointer_api.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1443 Fix missing translations and translation typos
  .github/workflows/unit_tests.yml
  .gitignore
  app/l10n.yaml
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  scripts/check_translations.sh
Labels: A2-technical, B0-low, C0-breaksnothing

#1455 Fix display of QR-code for big font sizes and small screens
  app/lib/common/components/qr_code_view/qr_code_image_view.dart
  app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
  app/lib/page/assets/qr_code_printing/pages/qr_code_share_or_print_view.dart
  app/lib/page/assets/receive/receive_page.dart
Labels: A1-bugfix, B2-critical, C0-breaksnothing
