Repository encointer/encointer-wallet-flutter, pull requests merged in 2023-06, with the labels that each got.

#1241 TX History UX: move it to main page and change transaction tile design
  app/assets/images/assets/receive_square_2.svg
  app/lib/gen/assets.gen.dart
  app/lib/models/transfer/transfer_history.dart
  app/lib/modules/transfer/logic/transfer_history_view_store.dart
  app/lib/modules/transfer/view/transfer_history_view.dart
  app/lib/modules/transfer/widgets/transaction_card.dart
  app/lib/modules/transfer/widgets/transactions_list.dart
  app/lib/page/assets/index.dart
  app/lib/page/assets/transfer/transfer_page.dart
  app/lib/utils/translations/translations_transaction.dart
  app/test_driver/app/home/home_helper.dart
  app/test_driver/app/transfer/transfer_helper.dart
  app/test_driver/app_test.dart
Labels: A0-ux, A2-technical, B1-medium, C0-breaksnothing

#1212 Integration tests with devmode qr codes
  app/lib/modules/settings/logic/app_settings_store.dart
  app/lib/modules/settings/logic/app_settings_store.g.dart
  app/lib/page-encointer/home_page.dart
  app/lib/page/assets/transfer/transfer_page.dart
  app/lib/page/profile/contacts/contact_page.dart
  app/lib/page/qr_scan/qr_codes/contact.dart
  app/lib/page/qr_scan/qr_codes/invoice.dart
  app/lib/page/qr_scan/qr_scan_page.dart
  app/lib/router/app_router.dart
  app/lib/utils/translations/translations_assets.dart
  app/lib/utils/translations/translations_profile.dart
  app/test_driver/app.dart
  app/test_driver/app/contact/contact_keys.dart
  app/test_driver/app/contact/contact_test.dart
  app/test_driver/app/dev_qr_codes/dev_qr_code_keys.dart
  app/test_driver/app/dev_qr_codes/dev_qr_codes_test.dart
  app/test_driver/app/dev_qr_codes/dev_qr_codes_test_helpers.dart
  app/test_driver/app/navigate.dart
  app/test_driver/app/transfer/transfer_helper.dart
  app/test_driver/app/transfer/transfer_keys.dart
  app/test_driver/app/transfer/transfer_test.dart
  app/test_driver/app_test.dart
Labels: F0-pure flutter, A2-technical, B1-medium, C0-breaksnothing

#1252 [app_service] fix typo: Deutch -> Deutsch
  app/lib/modules/settings/service/app_service.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1250 Remove obsolete account password dialog
  app/lib/common/components/password_input_dialog.dart
  app/lib/page/assets/index.dart
  app/lib/page/profile/account/account_manage_page.dart
  app/lib/page/profile/index.dart
  app/lib/service/tx/lib/src/submit_tx_wrappers.dart
  app/lib/utils/alerts/app_alert.dart
  app/lib/utils/alerts/password_input_dialog.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1251 Fix softwrap in Tx-History button
  app/lib/page/assets/index.dart
  app/lib/utils/translations/translations_assets.dart
  app/lib/utils/translations/translations_home.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1245 Migrate to Material 3
  app/lib/common/components/rounded_card.dart
  app/lib/modules/transfer/widgets/transaction_card.dart
  app/lib/page/network_select_page.dart
  app/lib/theme/custom/colors/app_colors.dart
  app/lib/theme/custom/components/components_theme.dart
  app/lib/theme/custom/custom_theme.dart
  app/test_driver/app/profile/profile_helper.dart
  app/test_driver/app/transfer/transfer_helper.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1238 integration test for vouchers
  app/lib/page/assets/index.dart
  app/lib/page/reap_voucher/dialogs.dart
  app/lib/page/reap_voucher/reap_voucher_page.dart
  app/test_driver/app/home/home_test.dart
  app/test_driver/app/voucher/voucher_integration_test.dart
  app/test_driver/app_test.dart
  app/test_driver/helpers/extension/screenshots_name.dart
  melos.yaml
  pubspec.lock
Labels: A2-technical, B0-low, C0-breaksnothing

#1224 Bazaar - Create UI for main page of Bazaar
  app/lib/models/bazaar/businesses.dart
  app/lib/models/bazaar/businesses.g.dart
  app/lib/page-encointer/bazaar/0_main/bazaar_main.dart
  app/lib/page-encointer/new_bazaar/logic/businesses_store.dart
  app/lib/page-encointer/new_bazaar/logic/businesses_store.g.dart
  app/lib/page-encointer/new_bazaar/view/businesses_view.dart
  app/lib/page-encointer/new_bazaar/widgets/businesses_card.dart
  app/lib/page-encointer/new_bazaar/widgets/dropdown_widget.dart
  app/lib/router/app_router.dart
  app/lib/utils/translations/translations_bazaar.dart
Labels: A0-ux, A2-technical, B0-low, C0-breaksnothing

#1266 Bump dependencies
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/lib/common/components/map/encointer_map.dart
  app/lib/page-encointer/bazaar/menu/2_my_businesses/businesses_on_map.dart
  app/lib/page-encointer/meetup/scan_claim_qr_code.dart
  app/lib/page/qr_scan/qr_scan_page.dart
  app/lib/service/notification/lib/src/notification_plugin.dart
  app/pubspec.lock
  app/pubspec.yaml
  packages/ew_storage/pubspec.yaml
Labels: A2-technical, B0-low, C0-breaksnothing

#1291 Typo On Transfers Screen
  app/lib/l10n/arb/app_en.arb
  app/lib/modules/transfer/logic/transfer_history_view_store.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1277 Write test for Bazaar's main page mock
  app/lib/page-encointer/new_bazaar/view/businesses_view.dart
  app/lib/page-encointer/new_bazaar/widgets/empty_businesses.dart
  app/test/store/bazaar/businesses_store_test.dart
Labels: A2-technical, B0-low, C0-breaksnothing

#1276 Bug: Send Button doesn't work, if Address is not in the address book.
  app/lib/common/components/address_input_field.dart
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1299 [assets-page] fix button layout that was accidentally unfixed
  app/lib/page/assets/index.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1298 [tx-payment-confirmation-page] show address and label and don't format label as address
  app/lib/page/assets/transfer/payment_confirmation_page/components/payment_overview.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1296 Tx History: Fix naming of Community Issued Income
  app/lib/config/prod_community.dart
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/models/transfer/transfer_history.dart
  app/lib/modules/transfer/widgets/transaction_card.dart
Labels: A0-ux, B2-critical, C0-breaksnothing

#1304 UI Bug v1.10.0: Autofitting of Transfers Screen for small devices doesn't work
  app/lib/modules/transfer/widgets/transaction_card.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1308 Add explainer for the end of the tx history
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/modules/transfer/widgets/transactions_list.dart
Labels: A1-bugfix, A2-technical, B0-low, C0-breaksnothing

#1313 Fix non-Enlish community messages
  app/lib/page/assets/announcement/logic/announcement_store.dart
  app/lib/page/assets/announcement/logic/announcement_store.g.dart
  app/lib/page/assets/announcement/view/announcement_view.dart
  app/lib/page/assets/announcement/widgets/announcement_card.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1307 Implement flow to enable biometrics
  app/lib/config/biometiric_auth_state.dart
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/main.dart
  app/lib/modules/login/logic/login_store.dart
  app/lib/modules/login/logic/login_store.g.dart
  app/lib/modules/login/view/login_view.dart
  app/lib/modules/settings/logic/app_settings_store.dart
  app/lib/modules/settings/logic/app_settings_store.g.dart
  app/lib/modules/settings/service/app_service.dart
  app/lib/modules/splash/view/splash_view.dart
  app/lib/page-encointer/common/community_chooser_on_map.dart
  app/lib/page/profile/index.dart
  app/lib/presentation/home/views/home_page.dart
  app/lib/router/app_router.dart
  app/lib/service/auth/local_auth_service.dart
  app/lib/utils/alerts/app_alert.dart
  app/test_driver/app/account/account_test.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1314 Bug Community Messages: Sorting of Messages is upside down
  app/lib/page/assets/announcement/logic/announcement_store.dart
  app/lib/page/assets/announcement/logic/announcement_store.g.dart
  app/lib/page/assets/announcement/view/announcement_view.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1323 Fix: Initialize the locale with system language
  app/lib/modules/settings/logic/app_settings_store.dart
  app/lib/modules/settings/service/app_service.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1321 truncate numbers in transfer history to 4 decimals
  app/lib/models/transfer/transfer_history.dart
  app/lib/models/transfer/transfer_history.g.dart
  app/lib/utils/extensions/double/double_extension.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement, F0-pure flutter, A0-ux, B1-medium, C0-breaksnothing

#1328 tx history: icons should be the same colour as the numbers
  app/lib/modules/transfer/widgets/transaction_card.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1325 Fix Ceremony Cycle Progress Bar
  app/lib/page-encointer/ceremony_box/components/ceremony_progress_bar.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1309 Only ask for authentication in certain cases
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/main.dart
  app/lib/modules/account/logic/new_account_store.dart
  app/lib/modules/account/logic/new_account_store.g.dart
  app/lib/modules/account/view/add_account_view.dart
  app/lib/modules/account/view/create_pin_view.dart
  app/lib/modules/account/view/handle_new_account_result_mixin.dart
  app/lib/modules/account/view/import_account_view.dart
  app/lib/modules/login/logic/login_store.dart
  app/lib/modules/login/logic/login_store.g.dart
  app/lib/modules/login/login.dart
  app/lib/modules/login/service/login_service.dart
  app/lib/modules/login/view/login_dialog.dart
  app/lib/modules/login/view/login_view.dart
  app/lib/modules/login/widget/login_button.dart
  app/lib/modules/login/widget/pin_dots.dart
  app/lib/modules/login/widget/pin_keyboard.dart
  app/lib/modules/login/widget/widget.dart
  app/lib/modules/settings/logic/app_settings_store.dart
  app/lib/modules/settings/logic/app_settings_store.g.dart
  app/lib/modules/settings/service/app_service.dart
  app/lib/modules/splash/view/splash_view.dart
  app/lib/page-encointer/common/community_chooser_on_map.dart
  app/lib/page/assets/transfer/payment_confirmation_page/index.dart
  app/lib/page/profile/account/account_manage_page.dart
  app/lib/page/profile/account/change_password_page.dart
  app/lib/page/profile/index.dart
  app/lib/presentation/home/views/home_page.dart
  app/lib/router/app_router.dart
  app/lib/service/substrate_api/encointer/encointer_api.dart
  app/lib/store/app.dart
  app/lib/store/settings.dart
  app/lib/store/settings.g.dart
  app/lib/utils/alerts/app_alert.dart
  app/lib/utils/alerts/password_input_dialog.dart
  app/test/store/account_test.dart
  app/test/store/app_test.dart
  app/test/store/encointer/encointer_test.dart
  app/test/store/encointer/sub_stores/community_store/community_store_test.dart
  app/test/store/settings_test.dart
  app/test_driver/app.dart
  app/test_driver/app/account/account_test.dart
  app/test_driver/app/account_manage/account_manage_test.dart
  app/test_driver/app/app.dart
  app/test_driver/app/login/login_test.dart
  app/test_driver/app/profile/profile_test.dart
  app/test_driver/app_test.dart
  app/test_driver/helpers/command/app_functions.dart
  app/test_driver/helpers/command/test_command.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#1326 [Tx-History] fix showing contact names
  app/lib/modules/transfer/widgets/transaction_card.dart
  app/lib/modules/transfer/widgets/transactions_list.dart
  app/lib/store/settings.dart
Labels: A0-ux, B1-medium, C0-breaksnothing
