Repository encointer/encointer-wallet-flutter, pull requests merged in 2024-09, with the labels that each got.

#1698 support system.remark on account manage page
  app/lib/l10n/arb/app_de.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_fr.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/l10n/arb/app_sw.arb
  app/lib/page/profile/account/account_manage_page.dart
  app/lib/page/profile/account/benefits.dart
  app/lib/page/profile/account/remark.dart
  app/lib/service/tx/lib/src/submit_tx_wrappers.dart
  app/lib/service/tx/lib/src/tx_notification.dart
Labels: F1-shallow-encointer-domain, A0-ux, A2-technical, B0-low, C0-breaksnothing

#1699 Make democracy production
  app/lib/page/profile/index.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#1700 Fix notifications on Android
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/lib/service/notification/lib/src/ceremony_notifications.dart
  app/lib/service/notification/lib/src/notification_plugin.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1701 fix german typos
  app/lib/l10n/arb/app_de.arb
Labels: A1-bugfix, B0-low, C0-breaksnothing

#1703 [Democracy] fix clipped proposal id on small phones
  app/lib/page-encointer/democracy/democracy_page.dart
  app/lib/page-encointer/democracy/widgets/proposal_tile.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing
